ornikar/eslint-configs

@ornikar/eslint-config/README.md
Je complèterais un peu plus la partie lerna quand je ferais le generator
=> docs(eslint-config): improve readme with guidelines ARCH-823

@ornikar/eslint-config/rules/code-quality.js
fixes https://github.com/ornikar/eslint-configs/discussions/10
=> feat: remove max-lines rule [no issue]

@ornikar/eslint-config/rules/style.js
Implement proposal https://github.com/ornikar/eslint-configs/discussions/20
=> feat: change `import/order` to sort imports alphabetically ARCH-1183

@ornikar/eslint-config/rules/node-override.js, @ornikar/eslint-config/tests/node/.eslintrc.json, @ornikar/eslint-config/tests/node/restricted-syntax.js, @ornikar/eslint-config/tests/restricted-syntax.js
error in filter.
I added a test so that's now tested.
=> fix(eslint-config): node restricted-syntax [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/exports.ts, @ornikar/eslint-config-typescript/tests/no-unused-vars.ts, @ornikar/eslint-config-typescript/tests/template-expressions.ts
- https://github.com/ornikar/eslint-configs/discussions/30
- https://github.com/ornikar/eslint-configs/discussions/31
- https://github.com/ornikar/eslint-configs/discussions/32
=> feat: enable three typescript-eslint rules [no issue]

@ornikar/eslint-config-typescript/tests/consistent-type-definitions.ts
It seems I forgot to commit files
=> test(eslint-config-typescript): add missing tests [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/consistent-indexed-object-style.ts
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2723058534/2021-07-20
https://github.com/ornikar/eslint-configs/discussions/74
=> feat(eslint-config-typescript): enable rule consistent-indexed-object-style ARCH-1485

@ornikar/eslint-config-typescript-react/tests/react-native/index.tsx, @ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/consistent-type-imports.ts
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2723058534/2021-07-20
https://github.com/ornikar/eslint-configs/discussions/73
=> feat(eslint-config-typescript): enable rule consistent-type-imports ARCH-1486

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/non-nullable-type-assertion-style.ts
https://github.com/ornikar/eslint-configs/discussions/64
=> feat: enable @typescript-eslint/non-nullable-type-assertion-style ELN-1717

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/prefer-array-some.js
Explain here why this PR is needed
If needed, explain here the solution you chose for this
=> feat: add unicorn/prefer-array-some linting rule [no issue]

@ornikar/eslint-config-typescript/tests/import-exports.ts, @ornikar/eslint-config/_shared.js, @ornikar/eslint-config/package.json, @ornikar/eslint-config/rules/sort-imports-exports.js, @ornikar/eslint-config/tests/module/.eslintrc.json, @ornikar/eslint-config/tests/module/restricted-syntax.js, @ornikar/eslint-config/tests/node/exports.mjs, @ornikar/eslint-config/tests/node/import-exports.mjs, yarn.lock
https://github.com/ornikar/eslint-configs/discussions/107
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2915827789/2021-11-16
=> feat: sort imports and exports [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/prefer-date-now.js
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-date-now.md
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2915827789/2021-11-16
=> feat: enable prefer-date-now [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/switch-exhaustiveness-check.ts, @ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/prefer-switch.js
cf : https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2900202268/2021-10-19
Set `unicorn/prefer-switch` rule to `error`
Set `@typescript-eslint/switch-exhaustiveness-check` rule to `warn` (not autofixable)
=> feat: set up prefer-switch rule [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/prefer-regexp-test.js
cf: https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2900202268/2021-10-19
=> feat: set unicorn/prefer-regexp-test rule to error [no issue]

@ornikar/eslint-config-typescript/tests/prefer-string-starts-ends-with.ts, @ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/prefer-at.js
cf : https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2915827789/2021-11-16
=> feat: set unicorn/prefer-at rule to error [no issue]

@ornikar/eslint-config-react/stories-override.js, @ornikar/eslint-config-typescript-react/stories-override.js
Generalize overrides we add on each project
Usage:
```json
{
"overrides": [
{
"files": ["stories/*.stories.{ts,tsx}"],
"extends": ["@ornikar/eslint-config-typescript-react/stories-override"]
},
]
}
```
=> feat: add stories-override [no issue]

@ornikar/eslint-config-babel/package.json, @ornikar/eslint-config-formatjs/package.json, @ornikar/eslint-config-react/package.json, @ornikar/eslint-config-typescript-react/package.json, @ornikar/eslint-config-typescript/package.json, @ornikar/eslint-config/package.json
=> fix: downgrade node requirement [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/no-useless-length-check.js
https://github.com/ornikar/eslint-configs/discussions/157
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2952265854/2021-12-07
=> feat(eslint-config): enable unicorn/no-useless-length-check [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/naming-convention.ts
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2931687636/Styled+Components+Guidelines#Use-transient-props
=> fix(eslint-config-typescript): boolean prefix styled-components transient properties [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/naming-convention.ts
=> feat: add naming convention on parameters DR-1800

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/no-useless-fallback-in-spread.js
[#157](https://github.com/ornikar/eslint-configs/discussions/157)
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3068364532/2022-03-03
=> feat(eslint-config): enable unicorn/no-useless-fallback-in-spread [no issue]

@ornikar/eslint-config/rules/unicorn.js
On passe prefer-array-some de warn à error
=> feat: prefer-array-some is now in error mode [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/require-array-join-separator.js
Discussion: #147
Confluence: https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3068364532/2022-03-03
=> feat(eslint-config): require array join separator [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/no-invalid-void-type.ts
[https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-invalid-void-type.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-invalid-void-type.md)
=> feat: no invalid void type rule [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/prefer-reduce-type-parameter.ts
[#69](https://github.com/ornikar/eslint-configs/discussions/69)
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3203006465/2022-05-02
=> feat(eslint-config): enable typescript-eslint/prefer-reduce-type-parameter [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/expiring-todo-comments.js
Ignorer les dates + autoriser les tickets JIRA [expiring-todo-comments.md](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/expiring-todo-comments.md)
=> feat: update expiring todo comments [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/prefer-native-coercion-functions.js
Discussion: https://github.com/ornikar/eslint-configs/discussions/292
Confluence: [https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3203006465/2022-05-02](https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3203006465/2022-05-02)
=> feat(eslint-config): prefer-native-coercion-functions [no issue]

@ornikar/eslint-config/rules/node-override.js
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3272376346/2022-06-07#Discussions%3A
n/no-process-exist is more restrictive and duplicate of unicorn/no-process-exit
=> feat: disable no-process-exit rule from eslint-plugin-node [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/no-array-push-push.js
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-push-push.md
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3272376346/2022-06-07
=> feat(eslint-config): no-array-push-push [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/consistent-generic-constructors.ts
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3327790255/2022-08-02
[#343](https://github.com/ornikar/eslint-configs/discussions/343)
=> feat(eslint-config-typscript): add consistent-generic-constructors [no issue]

@ornikar/eslint-config-react/rules/react.js, @ornikar/eslint-config-react/tests/JSXQuotes.js
Enable now that edge cases are supported
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3327790255/2022-08-02
=> feat(jsx-curly-brace-presence): removing disable [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/relative-url-style.js
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3406007453/2022-09-06
#287
=> feat(unicorn): add relative-url-style [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/no-unreadable-iife.js
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3406007453/2022-09-06
#291
=> feat(unicorn): add no-unreadable-iife [no issue]

@ornikar/eslint-config/index.js, @ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/prefer-logical-operator-over-ternary.js
Eslint Meeting : [2022-09-06](https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3406007453/2022-09-06)
Jira : [INS-1931](https://ornikar.atlassian.net/browse/INS-1931)
=> feat: add prefer-logical-operator-over-ternary INS-1931

@ornikar/eslint-config-react/tests/react-testing-library/await-async-utils.js, @ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/catch-error-name.js
Ornikar discussion: https://github.com/ornikar/eslint-configs/discussions/274
sindresorhus/eslint-plugin-unicorn/issues/167
[Clean Code #chapter-2](https://github.com/jnguyen095/clean-code/blob/master/Clean.Code.A.Handbook.of.Agile.Software.Craftsmanship.pdf)
=> feat: update param name of unicorn/catch-error-name from err to error ING-666

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/no-thenable.js
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3460333630/2022-10-04
#285
=> feat(eslint-config): enable no-thenable rule [no issue]

.github/CODEOWNERS
- https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3411607717/Maintainers
- https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3456139296/Chapter+Frontend+Education+5+-+03+10+2022
- https://github.com/orgs/ornikar/teams/frontend-eslint-maintainers/members
=> chore: add codeowners ARCH-1581

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/naming-convention.ts
enforce https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2554331209/Naming+Types
should prevent comments like https://github.com/ornikar/learner-apps/pull/4407#discussion_r1005863811 in reviews
=> feat(eslint-config-typescript): add rules to naming convention [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/no-useless-promise-resolve-reject.js
Enable eslint rule unicorn/no-useless-promise-resolve
Turn eslint rule unicorn/no-useless-promise-resolve to "error" and create tests
=> feat: enable unicorn/no-useless-promise-resolve ECF-55

@ornikar/eslint-config-typescript/allow-unsafe.js, @ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/no-unsafe-declaration-merging.ts
#425 
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3503882314/2022-11-02
=> feat(eslint-config): add no unsafe declaration merging rule [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/no-unnecessary-await.js
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-unnecessary-await.md
We add it
=> feat: add unnecessary await unicorn rule [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/radix.js, @ornikar/eslint-config/tests/require-number-to-fixed-digits-argument.js
Checks that we always provide an argument to toFixed
Also added a test for the radix rule from airbnb
=> feat(eslint-unicorn): add eslint rules required to fixed argument [no issue]

@ornikar/eslint-config-react/monorepo-override.js, @ornikar/eslint-config-react/rules/react-testing-library-base-monorepo-override.js, @ornikar/eslint-config-react/tests/monorepo/.eslintrc.json, @ornikar/eslint-config-react/tests/monorepo/consistent-data-testid.js, @ornikar/eslint-config-typescript-react/monorepo-override.js
https://ornikar.slack.com/archives/CC9F4CTDH/p1673946294540689
- Add monorepo-override
- Add maximum prefix allowed
=> feat: improve data testid with monorepo override [no issue]

@ornikar/eslint-config/rules/unicorn.js, @ornikar/eslint-config/tests/array-reduce.js
https://ornikar.slack.com/archives/C016WFY0CUB/p1677774835477339
=> feat(eslint-config): unicorn no-array-reduce with configured allowSimpleOperations [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js
https://ornikar.slack.com/archives/CC9F4CTDH/p1683098918258879?thread_ts=1680613522.149929&cid=CC9F4CTDH
=> feat: remove boolean restrictions on naming convention rule [no issue]

@ornikar/eslint-plugin-ornikar/rules/typescript-no-unused-exports.js
improve ignore patterns to remove all issues in instructors-app
=> feat: eslint-plugin-ornikar improve ignoreFiles in typescript-no-unused-exports [no issue]

@ornikar/eslint-config-typescript/rules/typescript-eslint.js, @ornikar/eslint-config-typescript/tests/no-duplicate-type-constituents.ts
https://github.com/ornikar/eslint-configs/discussions/507
=> feat: enable @typescript-eslint/no-duplicate-type-constituents ECF-317
