@ornikar/eslint-config/rollup.js

We cannot place it in `@ornikar/rollup-config`, eslint expects it under `@scope/eslint-config(-*)?`
https://github.com/ornikar/shared-configs/pull/457

feat(eslint-config): add config for rollup ARCH-826

---

@ornikar/eslint-config-babel/README.md
@ornikar/eslint-config-react/README.md
@ornikar/eslint-config-react/index.js
@ornikar/eslint-config-react/package.json
@ornikar/eslint-config-react/tests/.eslintrc.json
@ornikar/eslint-config-typescript-react/README.md
@ornikar/eslint-config-typescript-react/package.json
@ornikar/eslint-config-typescript-react/react-native.js
@ornikar/eslint-config-typescript-react/rules/import.js
@ornikar/eslint-config-typescript-react/rules/react.js
@ornikar/eslint-config-typescript/README.md

BREAKING CHANGE: extending eslint-config-react will also require to extends eslint-config-babel

refactor: typescript react dont import babel [no issue]

---

@ornikar/eslint-config-react/index.js
@ornikar/eslint-config/index.js

- import/extensions is defined in airbnb-config-base
- it is not related to react
- when a package is "type": "module", "mjs" should be present in the import extension.
Move the rule in eslint-config

fix: move import/extensions rule in eslint-config [no issue]

---

@ornikar/eslint-config-typescript-react/rules/react.js
@ornikar/eslint-config-typescript-react/tests/react.tsx
@ornikar/eslint-config-typescript/rules/import.js
@ornikar/eslint-config-typescript/rules/typescript-eslint.js

Improve typescript-eslint config
- disable recommended import rules
- remove config already in extends
- reenable `react/no-unused-prop-types` which works with interface props definition

fix(eslint-config-typescript): better typescript eslint config [no issue]

---

@ornikar/eslint-config-react/rules/react.js
@ornikar/eslint-config-react/tests/Typography.js
@ornikar/eslint-config-typescript-react/tests/react.tsx
@ornikar/eslint-config-typescript/rules/typescript-eslint.js
@ornikar/eslint-config-typescript/tests/no-non-null-assertion.ts

https://github.com/ornikar/eslint-configs/discussions/23
https://github.com/ornikar/eslint-configs/discussions/28  
- Update `typescript-eslint.js` to add rule `@typescript-eslint/no-non-null-assertion` with `error` setting, to a new commented category called “'warn' to ‘error’”
- Update `eslint-configs/@ornikar/eslint-config-react/rules/react.js` to add `react/function-component-definition` rule with proposed code in repository rule discussion

feat: add rules for eslint meeting ARCH-1376

---

@ornikar/eslint-config-react/react-native.js
@ornikar/eslint-config-react/rules/react-native.js
@ornikar/eslint-config-typescript-react/react-native.js
@ornikar/eslint-config-typescript-react/tests/react-native/.eslintrc.json
@ornikar/eslint-config-typescript-react/tests/react-native/MyComponent.ios.tsx
@ornikar/eslint-config-typescript-react/tests/react-native/index.tsx

Currently trying to import @ornikar/eslint-config-typescript-react/react-native imports @ornikar/eslint-config-babel
Split react-native config and import only rules in eslint-config-typescript-react

fix(eslint-config-typescript-react): fix import of react-native config [no issue]

---

renovate.json

We are not notified today about minor updates of eslint plugins. There are not either in the renovate dashboard issue.
This config should open the pr automaticly and notify us. We can then add the new rules in the discussions tab and merge the pr.

chore: config renovate to open prs automaticly [no issue]

---

@ornikar/eslint-config/rules/node-override.js

Added by christopher, but we should not use it in node for now

fix: disable unicorn/prefer-at for node [no issue]

---

@ornikar/eslint-config-typescript/rules/typescript-eslint.js

This rule was wrongly enabled in https://github.com/ornikar/eslint-configs/pull/159
Move it to 'warn' so that its still shows warning but doesn't need fixing right now

fix(eslint-config-typescript): no unsafe argument as warn [no issue]

---

@ornikar/eslint-config-react/rules/react.js

Our override causes issues with latest typescript-eslint update
airbnb rules matches our override but also fixes things
https://app.circleci.com/pipelines/github/ornikar/kitt/3536/workflows/6f6c619f-e17e-429a-b71e-a8eb2e2c5c36/jobs/24378

fix(eslint-config-react): stop overriding react/sort-comp [no issue]

---

@ornikar/eslint-config-typescript/rules/typescript-eslint.js

As decided in front COP, we want to enforce prefix booleans variables with a eslint warning.
Add a new `@typescript-eslint/naming-convention` rule to TS lint rules

feat(eslint-config-typescript): add prefixed boolean naming-convention [no issue]

---

@ornikar/eslint-config-typescript/rules/import.js

https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2952265854/2021-12-07
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2670330094/Avoid+default+export
error will be the new default, each legacy app can still override it to warn if necessary (in all app or only for some folders)

feat(eslint-config-typescript): import/no-default-export as error [no issue]

---

@ornikar/eslint-config-typescript/rules/typescript-eslint.js
@ornikar/eslint-config/utils.js

This rule is one of the slowest one, and give us no value either in cli or in CI. It only should help us in dev when we name things
TImings in learner-apps

feat: disable naming convention when eslint is not ran from vscode extension [no issue]

---

@ornikar/eslint-config-react/stories-override.js

Most of our warnings are in stories, most of them for decorators. We can allow without worry arrow functions for decorators, as they are not likely to change to functions with typescript generics.

feat(eslint-config-react): allow arrow functions in stories [no issue]

---

@ornikar/eslint-config-typescript/rules/typescript-eslint.js
@ornikar/eslint-config-typescript/tests/prefer-literal-enum-member.ts

[https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/prefer-literal-enum-member.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/prefer-literal-enum-member.md)

feat: add prefer-literal-enum-member rule [no issue]

---

@ornikar/eslint-config-typescript/rules/typescript-eslint.js
@ornikar/eslint-config-typescript/tests/no-unnecessary-type-constraint.ts

See https://github.com/ornikar/eslint-configs/discussions/75 and https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-unnecessary-type-constraint.md.
Add the `@typescript-eslint/no-unnecessary-type-constraint` to `@ornikar/eslint-config-typescript` as an error as it is auto-fixable.

feat(eslint-config-typescript): add @typescript-eslint/no-unnecessary-type-constraint [no issue]

---

@ornikar/eslint-config-react/rules/react.js
@ornikar/eslint-config-react/tests/ComponentWithTestId.js
@ornikar/eslint-config-react/tests/consistent-data-testid.js

Add [testing-library/consistent-data-testid](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/consistent-data-testid.md) rule.
- Regex is following the rule from https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3048375320/Testing+Library+draft#Name-your-test-IDs-properly
- Rule is in the shared config and not the tests-override as we don't want to see the error after writing the testId. It allows us to check the testId for e2e tests too
- It's a warning for now, the naming convention could change now that we'll use it and there are a LOT of test id in certain codebases

feat(eslint-config-react): add testing-library/consistent-data-testid rule [no issue]

---

@ornikar/eslint-config-react/tests-override.js
@ornikar/eslint-config-react/tests/react-testing-library/consistent-data-testid.js

Disable `testing-library/consistent-data-test-id` for tests. This enables direct usage of test-id in tests file (see [react-forms-universal example](https://github.com/ornikar/components/blob/82fe8a0b020cad0a5fa721982f83a13271c1730c/@ornikar/react-forms-universal/src/Field/index.native.test.tsx))
- Disable the rule in `tests-override`

feat(eslint-config-react): disable consistent-data-testid on tests [no issue]

---

@ornikar/eslint-config-react/rules/react-native.js
@ornikar/eslint-config-react/tests/react-native/.eslintrc.json
@ornikar/eslint-config-react/tests/react-native/forbid-component-props.js

To handle test ids on both web and native apps we need to pass the testID prop to kitt-universal components.
For web components the prop used is data-testid and for native components it’s testID
Passing the testID prop to a component handled by react-native-web (View, Text, TextInput) will convert it to data-testid when rendering the DOM.
Passing the data-testid prop to a component won't used when rendering the DOM.
Jira : [INS-1880](https://ornikar.atlassian.net/browse/INS-1880)
`data-testid` will be forbidden on React Native components, but still useable on dom elements

feat(eslint-config): add forbid-component-props for data-testid INS-1880

---

@ornikar/eslint-config-react/rules/react-native.js

Eslint Meeting : [2022-09-06](https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3406007453/2022-09-06)
Jira : [INS-1926](https://ornikar.atlassian.net/browse/INS-1926)
The rule ‘react/prefer-stateless-function' was deactivated for react native for a long time when stateless function were introduced and didn’t work with react native, now that react native supports them we want to reactivate the rule.
Added the rule and ran linter on selfcare, instructor and learner without issue

feat: remove prefer-stateless-function from react-native INS-1926

---

@ornikar/eslint-config-react/_shared.js
@ornikar/eslint-config-react/rules/react-testing-library-base.js
@ornikar/eslint-config-react/rules/react-testing-library-tests.js
@ornikar/eslint-config-react/rules/react.js
@ornikar/eslint-config-react/tests-override.js
@ornikar/eslint-config-typescript-react/_shared.js
@ornikar/eslint-config-typescript-react/tests-override.js

Currently, with `eslint-config-typescript-react/tests-override`, `consistent-data-testid` is not off because it is only off on non-typescript projects
Instead of duplicating the `off`, I splitted testing-library configs in eslint-config-react for base (source files) and tests (override).
Also, the `react` config is no longer linked to the plugin `testing-library` which makes more sense as the config is currently splitted by plugins.

fix: fix react-testing-library override for typescript-react [no issue]

---

@ornikar/eslint-config-react/stories-override.js
@ornikar/eslint-config-react/tests/stories/.eslintrc.json
@ornikar/eslint-config-react/tests/stories/Avatar.stories.js

Allow to use CSF format with `export default` as shown in test example

feat(eslint-config-react): allow default export in stories for CSF [no issue]

---

@ornikar/eslint-config/rules/node.js

[node/shebang](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/shebang.md) rule is enabled by default.
> This rule checks bin field of package.json, then if a target file matches one of bin files, it checks whether or not there is a correct shebang. Otherwise it checks whether or not there is not a shebang.
This automatically remove `#!/usr/bin/env node` inside our scripts, but we want them.
➡️ This PR disable `node/shebang` for our script (files inside `/scripts` folder)

feat: disable node/shebang for our js scripts [no issue]

---

@ornikar/eslint-config/_shared.js
@ornikar/eslint-config/rules/imports.js
@ornikar/eslint-config/tests/node-module/prefer-export-from/prefer-export-from-fail-1.js
@ornikar/eslint-config/tests/node-module/prefer-export-from/prefer-export-from-fail-2.js
@ornikar/eslint-config/tests/node-module/prefer-export-from/prefer-export-from-pass-1.js
@ornikar/eslint-config/tests/node-module/prefer-export-from/prefer-export-from-pass-2.js
@ornikar/eslint-config/tests/node-module/prefer-export-from/prefer-export-from.js

Now that we use imports in mjs files, we have to configure eslint-config too.

fix: configure imports for base config [no issue]

---

@ornikar/eslint-config-typescript/rules/typescript-eslint.js
@ornikar/eslint-config-typescript/tests/no-unnecessary-boolean-literal-compare.ts

Implements https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare, see https://github.com/ornikar/eslint-configs/discussions/645.

feat(eslint-config-typescript): add @typescript-eslint/no-unnecessary-boolean-literal-compare [no issue]

---

@ornikar/eslint-config-typescript/rules/typescript-eslint.js
@ornikar/eslint-config-typescript/tests/no-unnecessary-condition.ts

Implements https://typescript-eslint.io/rules/no-unnecessary-condition/, see https://github.com/ornikar/eslint-configs/discussions/646

feat(eslint-config-typescript): implement no-unnecessary-condition [no issue]

---

@ornikar/eslint-config-typescript/rules/typescript-eslint.js

On veut passer cette règle en warn car on se contente pour le moment de la désactiver/la mettre en warn partout, car en erreur cette règle peut être dangereuse

feat(eslint-config-typescript): use warn for no-unnecessary-condition rule OSE-9446
